name: 'ContextHound Scan'
description: 'Scan LLM prompts for injection and security risks'
author: 'ContextHound'

inputs:
  threshold:
    description: 'Risk score threshold (0-100). Fails if score >= threshold.'
    required: false
    default: '60'
  fail-on:
    description: 'Fail on first finding of severity: critical|high|medium'
    required: false
    default: ''
  sarif-out:
    description: 'Path to write SARIF output'
    required: false
    default: 'results.sarif'
  config:
    description: 'Path to .contexthoundrc.json config file'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ github.workspace }}

    - name: Run ContextHound scan
      shell: bash
      run: |
        ARGS="--format console,sarif --out ${{ inputs.sarif-out }} --threshold ${{ inputs.threshold }}"
        if [ -n "${{ inputs.fail-on }}" ]; then
          ARGS="$ARGS --fail-on ${{ inputs.fail-on }}"
        fi
        if [ -n "${{ inputs.config }}" ]; then
          ARGS="$ARGS --config ${{ inputs.config }}"
        fi
        npx hound scan $ARGS
      working-directory: ${{ github.workspace }}

    - name: Upload SARIF to GitHub Code Scanning
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.sarif-out }}
